### ISSUE TITLE
script stops when running from / but one volume is not mounted - how to check / ?

### ISSUE THREAD

**Issue by miczac** [briankendall/check-time-machine#1]
Hello, __many__ thanks for this script!
This is on macOS 10.12.6, trying to back up a couple of external volumes.
```
$ sudo python ~/Downloads/checktimemachine.py 
*** Checking volume: 230GB-1
Getting list of files from source volume...
...found 20000      
Done
Getting list of files from Time Machine backup...
...98%-ish complete      
Done

Comparing, 100% complete      
Done
*** Checking volume: DATA-1TB-01
Getting list of files from source volume...
Error: "" does not exist on disk. Cannot continue!
```
I suspect it's simply because this _DATA-1TB-01_ disk is not mounted but, of course, has backups.
Is there a chance to scan / without unmounting all the disks?
Thanks a lot - Michael.

**Comment by miczac** [comment]
I just did unmount all disks but the script fails:
```
$ sudo python ./checktimemachine.py 
*** Checking volume: 230GB-1
Getting list of files from source volume...
Error: "" does not exist on disk. Cannot continue!
```
Current workaround is a line like this:
```sudo find / -type d -maxdepth 1 ! -iname ".*" -exec python ./checktimemachine.py {} \;```
This is not hassle-free but works for the time being.

Alas my python knowledge is much less than basic.

**Comment by miczac** [comment]
```
$ sudo find / -type d -maxdepth 1 ! -iname ".*" -exec python ./checktimemachine.py {} \;
Not found: 
Getting list of files from source volume...
...found 600000      
Done
Getting list of files from Time Machine backup...
...100%-ish complete      
Done

Comparing, 100% complete      
Done
Determining which files are marked as excluded...

Non-excluded files not yet in backup, or missing from backup:
  (none)

Excluded files:
  (none)
Getting list of files from source volume...

Done
Getting list of files from Time Machine backup...
...100%-ish complete      
Done

Comparing, 100% complete      
Done
Determining which files are marked as excluded...

Non-excluded files not yet in backup, or missing from backup:
  (none)

Excluded files:
  (none)
Getting list of files from source volume...

Done
Getting list of files from Time Machine backup...

Done


Done
Determining which files are marked as excluded...

Non-excluded files not yet in backup, or missing from backup:
  (none)

Excluded files:
  (none)
Getting list of files from source volume...
Traceback (most recent call last):
  File "./checktimemachine.py", line 565, in <module>
    missing = findMissingFilesInFolder(volume, path)
  File "./checktimemachine.py", line 375, in findMissingFilesInFolder
    srcFiles = fileData(srcVolumePath, targetPath, isSrc=True)
  File "./checktimemachine.py", line 307, in fileData
    fileDataRec(result, path)
  File "./checktimemachine.py", line 296, in fileDataRec
    fileDataRec(data['dirs'][item], volumeRelativePath)
  File "./checktimemachine.py", line 296, in fileDataRec
    fileDataRec(data['dirs'][item], volumeRelativePath)
  File "./checktimemachine.py", line 283, in fileDataRec
    for item in os.listdir(os.path.join(volumePath, path)):
OSError: [Errno 20] Not a directory: '/dev/fd/3'
Getting list of files from source volume...

Done
Getting list of files from Time Machine backup...
Error: "home" does not exist in Time Machine backup. Cannot continue!
Getting list of files from source volume...
...found 385000      
Done
Getting list of files from Time Machine backup...
...99%-ish complete      
Done

Comparing, 100% complete      
Done
Determining which files are marked as excluded...
...100% complete      
Non-excluded files not yet in backup, or missing from backup:
  (none)

Excluded files:
  /Library/Preferences/Chromium/Default/History-journal
  /Library/Preferences/Chromium/Default/Favicons-journal
  /Library/Preferences/Chromium/Default/Favicons
  /Library/Preferences/Chromium/Default/History
  /Library/Preferences/Chromium/Safe Browsing Download
  /Library/Preferences/Chromium/Safe Browsing Module Whitelist
  /Library/Preferences/Chromium/Safe Browsing UwS List
  /Library/Preferences/Chromium/Safe Browsing Resource Blacklist
  /Library/Preferences/Chromium/Safe Browsing Download Whitelist
  /Library/Preferences/Chromium/Safe Browsing IP Blacklist
  /Library/Preferences/Chromium/Safe Browsing Extension Blacklist
  /Library/Preferences/Chromium/Safe Browsing Bloom
  /Library/Preferences/Chromium/Safe Browsing UwS List Prefix Set
  /Library/Preferences/Chromium/Safe Browsing Csd Whitelist
  /Library/Preferences/Chromium/Safe Browsing Bloom Prefix Set

Add excluded files?
NOTE: many files that are marked as excluded really are meant
to be excluded. This tool is a rather blunt one and will only
add all of the excluded files in one batch. If there are files
listed here that you do want excluded, consider modifying the
'userIgnore' variable in this script, or individually adding
them yourself using 'tmutil removeexclusion path-to-file'.

(Basically, if you don't know what this all means or are
unsure what to do, you probably do NOT want to do this.)

Proceed? [y/N]
N
Getting list of files from source volume...

Done
Getting list of files from Time Machine backup...
Error: "net" does not exist in Time Machine backup. Cannot continue!
Getting list of files from source volume...

Done
Getting list of files from Time Machine backup...

Done


Done
Determining which files are marked as excluded...

Non-excluded files not yet in backup, or missing from backup:
  (none)

Excluded files:
  (none)
Getting list of files from source volume...
...found 10000      
Done
Getting list of files from Time Machine backup...
...99%-ish complete      
Done

Comparing, 100% complete      
Done
Determining which files are marked as excluded...
...100% complete      
Non-excluded files not yet in backup, or missing from backup:
  /private/var/audit/20180830110429.not_terminated
  /private/var/audit/20180830104543.20180830105014
  /private/var/audit/20180830102308.20180830104403
  /private/var/audit/20180830105921.20180830110429
  /private/var/audit/20180830104403.20180830104543
  /private/var/audit/20180830105014.20180830105921
  /private/var/audit/current
  /private/var/db/uuidtext/07/FAD1A8BC1F3A8789CE163124498A6F
  /private/var/db/uuidtext/10/8C34E4AD643CAA9B3AE93A6165E603

Excluded files:
  /private/var/db/dyld/dyld_shared_cache_i386.map
  /private/var/db/dyld/dyld_shared_cache_i386
  /private/var/db/dyld/dyld_shared_cache_x86_64
  /private/var/db/dyld/dyld_shared_cache_x86_64.map

Add excluded files?
NOTE: many files that are marked as excluded really are meant
to be excluded. This tool is a rather blunt one and will only
add all of the excluded files in one batch. If there are files
listed here that you do want excluded, consider modifying the
'userIgnore' variable in this script, or individually adding
them yourself using 'tmutil removeexclusion path-to-file'.

(Basically, if you don't know what this all means or are
unsure what to do, you probably do NOT want to do this.)

Proceed? [y/N]
N

Attempt to fix non-excluded files not in backup by:
 1. touching the files
 2. touching their containing directories
 3. changing their name and then changing it back again
...in the hopes that it'll actually do something helpful? [Y/n]
n
Getting list of files from source volume...

Done
Getting list of files from Time Machine backup...
...100%-ish complete      
Done

Comparing, 100% complete      
Done
Determining which files are marked as excluded...

Non-excluded files not yet in backup, or missing from backup:
  (none)

Excluded files:
  (none)
Getting list of files from source volume...
...found 320000      
Done
Getting list of files from Time Machine backup...
...100%-ish complete      
Done

Comparing, 100% complete      
Done
Determining which files are marked as excluded...

Non-excluded files not yet in backup, or missing from backup:
  (none)

Excluded files:
  (none)
Getting list of files from source volume...
...found 950000      
Done
Getting list of files from Time Machine backup...
...93%-ish complete      
Done

Comparing, 100% complete      
Done
Determining which files are marked as excluded...
...100% complete      
Non-excluded files not yet in backup, or missing from backup:
  /Users/mz/Library/Mail/V4/B4CAA886-9442-4E66-926D-D5A1249593B0/INBOX.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536018.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536045.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536046.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536040.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536075.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536021.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536067.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536064.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536038.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536034.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536050.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536025.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536041.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536037.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536068.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536031.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536032.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536020.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536023.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536071.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536044.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536054.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536027.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536042.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536035.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536073.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536019.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536070.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536065.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536049.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536060.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536029.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536066.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536052.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536039.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536072.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536024.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536026.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536057.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536074.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536022.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536047.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536056.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536058.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536063.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536033.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536028.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536036.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536053.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536030.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536051.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536043.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536062.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536055.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536061.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536059.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536048.emlx
  /Users/mz/Library/Mail/V4/91FBBB80-79B6-4CB6-B792-6C019AE6C854/SuperCollider.mbox/sc-dev.mbox/DDBE7378-8776-4E5E-B73D-9F8109E05BED/Data/6/3/5/Messages/536069.emlx
  /Users/mz/Library/Containers/com.apple.iWork.Pages/Data/Library/Application Support/Collaboration/com.apple.iWork

Excluded files:
  /Users/mz/florian.handy/WhatsApp/.trash/
  /Users/mz/Library/Calendars.ori/Calendar Cache
  /Users/mz/Library/Passes/ScheduledActivities.archive
  /Users/mz/Library/Passes/passes23.sqlite
  /Users/mz/Library/Passes/RemoteDevices.archive
  /Users/mz/Library/Passes/WebServiceTasks_v6.archive
  /Users/mz/Library/Passes/PaymentWebServiceContext.archive
  /Users/mz/Library/Passes/NotificationServiceTasks_v6.archive
  /Users/mz/Library/Mail/V4/MailData/Envelope Index
  /Users/mz/Library/Containers/com.apple.iWork.Numbers/Data/Library/Application Support/Collaboration/com.apple.iWork
  /Users/mz/Library/Containers/com.apple.Maps/Data/Library/Maps/Bookmarks.synced
  /Users/mz/Library/Assistant/SiriAnalytics.db
  /Users/mz/Library/Application Support/Chromium/Default/History-journal
  /Users/mz/Library/Application Support/Chromium/Default/Favicons-journal
  /Users/mz/Library/Application Support/Chromium/Default/Favicons
  /Users/mz/Library/Application Support/Chromium/Default/History
  /Users/mz/Library/Application Support/Chromium/Safe Browsing Download
  /Users/mz/Library/Application Support/Chromium/Safe Browsing Module Whitelist
  /Users/mz/Library/Application Support/Chromium/Safe Browsing UwS List
  /Users/mz/Library/Application Support/Chromium/Safe Browsing Resource Blacklist
  /Users/mz/Library/Application Support/Chromium/Safe Browsing Download Whitelist
  /Users/mz/Library/Application Support/Chromium/Safe Browsing IP Blacklist
  /Users/mz/Library/Application Support/Chromium/Safe Browsing Extension Blacklist
  /Users/mz/Library/Application Support/Chromium/Safe Browsing Bloom
  /Users/mz/Library/Application Support/Chromium/Safe Browsing UwS List Prefix Set
  /Users/mz/Library/Application Support/Chromium/Safe Browsing Csd Whitelist
  /Users/mz/Library/Application Support/Chromium/Safe Browsing Bloom Prefix Set
  /Users/mz/Library/Safari.ori/WebpageIcons.db
  /Users/mz/Library/Safari/CloudAutoFillCorrections.db
  /Users/mz/Library/Keyboard/de-dynamic.lm/
  /Users/mz/Library/Keyboard/en-dynamic.lm/
  /Users/mz/Library/Suggestions/
  /Users/mz/dev/sc3plugins/master/build/CMakeFiles/3.12.0/CompilerIdCXX/CompilerIdCXX.build/
  /Users/mz/dev/sc3plugins/master/build/CMakeFiles/3.12.0/CompilerIdC/
  /Users/mz/dev/sc3plugins/master/build/CMakeFiles/CMakeTmp/
  /Users/mz/dev/sc3.git/mz_sc_fork copy/build/
  /Users/mz/dev/sc3.git/3.7/build/
  /Users/mz/dev/sc3.git/supercollider-Version-3.7.0-beta1/build/CMakeFiles/3.4.1/CompilerIdC/
  /Users/mz/dev/sc3.git/supercollider-Version-3.7.0-beta1/build/CMakeFiles/3.4.1/CompilerIdCXX/
  /Users/mz/dev/sc3.git/supercollider-Version-3.7.0-beta1/build/CMakeFiles/CMakeTmp/
  /Users/mz/dev/sc3.git/mz_sc_fork/build.afterserverreorg/
  /Users/mz/dev/sc3.git/mz_sc_fork/build.3c0eb7f/
  /Users/mz/dev/sc3.git/mz_sc_fork/build/
  /Users/mz/dev/sc3.git/mz_sc_fork/build.lastworkingbeforeserverreorg/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/testsuite/server/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/CMakeFiles/3.12.0/CompilerIdC/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/CMakeFiles/3.12.0/CompilerIdCXX/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/CMakeFiles/CMakeTmp/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/editors/sc-ide/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/server/supernova/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/server/scsynth/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/server/plugins/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/lang/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/external_libraries/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme2/SuperCollider.build/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/CMakeFiles/3.12.0/CompilerIdC/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/CMakeFiles/3.12.0/CompilerIdCXX/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/CMakeFiles/CMakeTmp/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/editors/sc-ide/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/server/supernova/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/server/scsynth/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/server/plugins/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/lang/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/external_libraries/
  /Users/mz/dev/sc3.git/3.9/build-b4-4022/SuperCollider.build/
  /Users/mz/dev/sc3.git/3.9/build/testsuite/server/
  /Users/mz/dev/sc3.git/3.9/build/CMakeFiles/3.12.0/CompilerIdC/
  /Users/mz/dev/sc3.git/3.9/build/CMakeFiles/3.12.0/CompilerIdCXX/
  /Users/mz/dev/sc3.git/3.9/build/CMakeFiles/CMakeTmp/
  /Users/mz/dev/sc3.git/3.9/build/editors/sc-ide/
  /Users/mz/dev/sc3.git/3.9/build/server/supernova/
  /Users/mz/dev/sc3.git/3.9/build/server/scsynth/
  /Users/mz/dev/sc3.git/3.9/build/server/plugins/
  /Users/mz/dev/sc3.git/3.9/build/lang/
  /Users/mz/dev/sc3.git/3.9/build/external_libraries/
  /Users/mz/dev/sc3.git/3.9/build/SuperCollider.build/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme-original/CMakeFiles/3.12.0/CompilerIdC/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme-original/CMakeFiles/3.12.0/CompilerIdCXX/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme-original/CMakeFiles/CMakeTmp/
  /Users/mz/dev/sc3.git/3.9/build-nathans_new_default_theme-original/SuperCollider.build/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/testsuite/server/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/CMakeFiles/3.12.0/CompilerIdC/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/CMakeFiles/3.12.0/CompilerIdCXX/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/CMakeFiles/CMakeTmp/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/editors/sc-ide/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/server/supernova/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/server/scsynth/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/server/plugins/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/lang/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/external_libraries/
  /Users/mz/dev/sc3.git/3.9/build-60daca8/SuperCollider.build/
  /Users/mz/dev/sc3.git/3.9/build-new_tabs/CMakeFiles/3.12.0/CompilerIdC/
  /Users/mz/dev/sc3.git/3.9/build-new_tabs/CMakeFiles/3.12.0/CompilerIdCXX/
  /Users/mz/dev/sc3.git/3.9/build-new_tabs/CMakeFiles/CMakeTmp/
  /Users/mz/dev/sc3.git/3.9/build-new_tabs/SuperCollider.build/
  /Users/mz/dev/sc3.git/3.9.bak-92commits_ahead/build.shft_enter/
  /Users/mz/dev/sc3.git/3.9.bak-92commits_ahead/build/
  /Users/mz/dev.new/sc3/mz_fork/build/CMakeFiles/3.9.3/CompilerIdC/
  /Users/mz/dev.new/sc3/mz_fork/build/CMakeFiles/3.9.3/CompilerIdCXX/
  /Users/mz/dev.new/sc3/mz_fork/build/CMakeFiles/CMakeTmp/

Add excluded files?
NOTE: many files that are marked as excluded really are meant
to be excluded. This tool is a rather blunt one and will only
add all of the excluded files in one batch. If there are files
listed here that you do want excluded, consider modifying the
'userIgnore' variable in this script, or individually adding
them yourself using 'tmutil removeexclusion path-to-file'.

(Basically, if you don't know what this all means or are
unsure what to do, you probably do NOT want to do this.)

Proceed? [y/N]
N

Attempt to fix non-excluded files not in backup by:
 1. touching the files
 2. touching their containing directories
 3. changing their name and then changing it back again
...in the hopes that it'll actually do something helpful? [Y/n]
n
Getting list of files from source volume...
...found 200000      
Done
Getting list of files from Time Machine backup...
...100%-ish complete      
Done

Comparing, 100% complete      
Done
Determining which files are marked as excluded...

Non-excluded files not yet in backup, or missing from backup:
  (none)

Excluded files:
  (none)
Invalid path: /Volumes
```
